# Generated by Django 4.1.2 on 2022-10-28 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='namesmodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('myimage', models.ImageField(blank=True, null=True, upload_to='logistics/images/vehicles/%Y/')),
                ('mydocument', models.FileField(blank=True, null=True, upload_to='myfiles/')),
            ],
        ),
    ]
